lab5/lab5/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('note/', include('note.urls')),
    path('admin/', admin.site.urls),
]

lab5/note/urls.py
from django.urls import path

from . import views

app_name = 'note'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddNotaView.as_view(), name='add'),
]

lab5/note/models.py
from django.core.exceptions import ValidationError
from django.db import models

# Create your models here.


class Nota(models.Model):
    nr_matricol = models.IntegerField()
    materie = models.CharField(max_length=50)
    nota = models.IntegerField()

    def __str__(self):
        return '{0} {1} {2}'.format(self.nr_matricol, self.materie, self.nota)

    def clean(self):
        errors = dict()
        if self.nr_matricol < 1 or self.nr_matricol > 1000:
            errors['nr_matricol'] = ValidationError('Numarul matricol introdus nu este corect')
        if len(self.materie) < 4 or len(self.materie) > 20:
            errors['materie'] = ValidationError('Lungimea materiei este invalida')
        if self.nota < 1 or self.nota > 10:
            errors['nota'] = ValidationError('Nota introdusa nu este corecta')
        if errors:
            raise ValidationError(errors)

lab5/note/views.py
# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, CreateView

from note.models import Nota


class IndexView(ListView):
    template_name = 'note/index.html'

    def get_queryset(self):
        return Nota.objects.all()


class AddNotaView(CreateView):
    model = Nota
    fields = ['nr_matricol', 'materie', 'nota']

    def get_success_url(self):
        return reverse('note:index')

lab5/note/templates/note/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Note</title>
</head>
<body>
    {% if object_list %}
        <ul type="none">
        {% for nota in object_list %}
            <li>{{ nota }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Nu exista note.</p>
    {% endif %}
    <a href="{% url 'note:add' %}">Adauga nota</a>
</body>
</html>

lab5/note/templates/note/nota_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Adaugare nota</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Adauga">
    </form>
</body>
</html>